### ISSUE TITLE
Add t docs "why dpicker?"

### ISSUE THREAD

**Issue by Narretz** [soyuka/dpicker#5]
Especially for a plugins as ubiquitous as a date picker every new contender should have some notes on why people should use it over other date pickers and what sets it apart from the most popular ones

**Comment by soyuka** [comment]
1. Light and straightforward, especially easy to maintain (~400 sloc) and to extend or add functionalities (see `onChange` and `modifier` methods).
2. Framework agnostic, and no default css so that it fits well with foundation/bootstrap and angular/react
3. HTML attributes compatibility with `input[type="date"]` (adds a `format` attribute or option)

What I think is good, and isn't "logic" in every other date picker is that your input's `Date` instance is separated from the input real value:

```
const dpicker = new DPicker(input)

console.log(dpicker.model) //the Moment.js instance
console.log(dpicker.input) //the input value, a formatted date
```
